# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e711e08cb1e5c8aaca988bb208a3cbd"
name = "SEO PRO - All in One"
application_url = "https://www.seoproshop.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_online_store_pages,write_online_store_pages,read_content,write_content"

[auth]
redirect_urls = [ "https://www.seoproshop.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
